# Global variables
threads_high: 11
threads_mid: 4
threads_low: 1
benchmark: 1

# Directories
inputdir: "../input/180705_NB551088_0005_AHTLH3AFXX"
outdir: "../output"

# Reference file
reference_genome: "/mnt/omar/pipelines/icc/pipeline/ref/allchrom.Chr1ToChrM.validated.fa"

# Target files
icc_panel: "/mnt/omar/pipelines/icc/pipeline/ref/ICC_169Genes_Nextera_V4_ProteinCodingExons_overHang40bp.mergeBed.bed"
cds_panel: "/mnt/omar/pipelines/icc/pipeline/ref/ICC_169Genes_Nextera_V4_ProteinCodingExons.mergeBed.bed"
canontran_panel: "/mnt/omar/pipelines/icc/pipeline/ref/ICC_169Genes_Nextera_V4_ProteinCoding_CanonicalTrans.mergeBed.bed"

# Known variants
dbsnp: "/mnt/omar/pipelines/icc/pipeline/ref/hg19_dbSNP138.vcf"
omni: "/mnt/omar/pipelines/icc/pipeline/ref/1000G_omni2.5.hg19.vcf"
tenk: "/mnt/omar/pipelines/icc/pipeline/ref/1000G_phase1.snps.high_confidence.hg19.vcf"
tenk_indel: "/mnt/omar/pipelines/icc/pipeline/ref/1000G_phase1.indels.hg19.vcf"
hapmap: "/mnt/omar/pipelines/icc/pipeline/ref/hapmap_3.3.hg19.vcf"
mills: "/mnt/omar/pipelines/icc/pipeline/ref/Mills_and_1000G_gold_standard.indels.hg19.vcf"

# Tool-specific parameters
gatk:
  AddOrReplaceReadGroups:
    RGID: "1"
    RGLB: "lib1"
    RGPL: "illumina"
    RGPU: "unit1"
    RGSM: "20"
    RGCN: "Broad"
    RGDS: "ICC"
    validation_stringency: "SILENT"
  MarkDuplicates:
    validation_stringency: "LENIENT"
  HaplotypeCaller:
    dcovg: 1000

# VEP parameters
vep:
  cache_dir: "/path/to/vep/cache"
  fasta: "/path/to/vep/fasta"
