# Global variables
threads: 4
np_threads: 2
benchmark: 1
memory: "25g"
dcovg: 1000
Skip_size_Check: 1


# Directories
outdir: "../output"

# References and Target files
TargetFile: "/data/Store/Scripts/Research/TargetFiles/ICC_169Genes_Nextera_V4_ProteinCodingExons_overHang40bp.mergeBed.bed"
CDSFile: "/data/Store/Scripts/Research/TargetFiles/ICC_169Genes_Nextera_V4_ProteinCodingExons.mergeBed.bed"
CanonTranFile: "/data/Store/Scripts/Research/TargetFiles/ICC_169Genes_Nextera_V4_ProteinCoding_CanonicalTrans.mergeBed.bed"
Ref: "/Ref_files_to_Aswan/UCSChg19/allchrom.Chr1ToChrM.validated.fa"
ref_index: "/Ref_files_to_Aswan/UCSChg19/allchrom.Chr1ToChrM.validated.fa.fai"
dbSNP: "/Ref_files_to_Aswan/dbSNP138/hg19_dbSNP138.vcf"

# Tools parameters
gatk: 
  AddOrReplaceReadGroups:
    RGID: "1"
    RGLB: "lib1"
    RGPL: "illumina"
    RGPU: "unit1"
    RGSM: "20"
    RGCN: "Broad"
    RGDS: "ICC"
    validation_stringency: "SILENT"
