# Global variables
threads: 11
np_threads: 2
benchmark: 1
memory: "25g"
dcovg: 1000
Skip_size_Check: 1

# Directories
inputdir: "../input/180705_NB551088_0005_AHTLH3AFXX"
outdir: "../output"

# References and Target files
TargetFile: "/data/Store/Scripts/Research/TargetFiles/ICC_169Genes_Nextera_V4_ProteinCodingExons_overHang40bp.mergeBed.bed"
CDSFile: "/data/Store/Scripts/Research/TargetFiles/ICC_169Genes_Nextera_V4_ProteinCodingExons.mergeBed.bed"
CanonTranFile: "/data/Store/Scripts/Research/TargetFiles/ICC_169Genes_Nextera_V4_ProteinCoding_CanonicalTrans.mergeBed.bed"
dbSNP: "/Ref_files_to_Aswan/dbSNP138/hg19_dbSNP138.vcf"
target_file: "/path/to/target_file"

reference_genome: "/mnt/omar/pipelines/icc/pipeline/ref/allchrom.Chr1ToChrM.validated.fa"

# Tools parameters
gatk: 
  AddOrReplaceReadGroups:
    RGID: "1"
    RGLB: "lib1"
    RGPL: "illumina"
    RGPU: "unit1"
    RGSM: "20"
    RGCN: "Broad"
    RGDS: "ICC"
    validation_stringency: "SILENT"
  BaseRecalibrator:
    known_sites: "/path/to/known_sites.vcf"
    target: "/path/to/target_file"
  PrintReads:
    target: "/path/to/target_file"
  VariantFiltration:
    reference: "/path/to/reference.fa"
  HaplotypeCaller:
    reference: "/path/to/reference.fa"
  UnifiedGenotyper:
    reference: "/path/to/reference.fa"

# VEP parameters
vep:
  cache_dir: "/path/to/vep/cache"
  fasta: "/path/to/vep/fasta"
